# Generated by Django 5.0.3 on 2024-04-02 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='internapplication',
            name='is_registered',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='InternRegistration',
            fields=[
                ('intern_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('momo_number', models.CharField(max_length=20)),
                ('amount', models.CharField(choices=[('10000frs', '10000frs'), ('20000frs', '20000frs')], max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('has_paid', models.BooleanField(default=False)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application', to='base.internapplication')),
            ],
            options={
                'verbose_name': 'Registered Interns',
                'ordering': ('-created',),
            },
        ),
    ]
